//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int IdComment { get; set; }
        public System.DateTime dataAdd { get; set; }
        public int idTest { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string Answer4 { get; set; }
        public string Answer5 { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
